services:
  frontend:
    build:
      context: ./web-gen-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Reference to the .env file for development
    environment:
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}  # Use environment variable for the API key
    volumes:
      - ./web-gen-app:/app
    stdin_open: true
    tty: true
