name: Deploy Docker Compose App

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Set this secret in your repository
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Set this secret in your repository

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Verify application is running
        run: |
          curl -f http://localhost:3000 || exit 1
